### PR TITLE
I18n foundation - First translation delivery ...

### PR DESCRIPTION
**Pull request by schulz2**

### CODE REVIEW

**Comment by Alex-Cook4** [comment]
@schulz2 Thanks for the pull-request. 

Could please highlight the non-translation work that is in here? Are they associated with any current issues? 

Could you also open an issue for translation and tag this pull request as part of it?

**Comment by chanskw** [comment]
Not sure I understand.  What do you mean by non-translation work? They all look like translation work.

**Comment by chanskw** [comment]
This is the issue?  https://github.com/IBMStreams/streamsx.messaging/issues/274

**Comment by Alex-Cook4** [comment]
@chanskw Thanks for tagging with the issue. 

>Not sure I understand. What do you mean by non-translation work? They all look like translation work.
@chanskw You're right. I was thrown off by some of the commit descriptions, but they're referring to the translation messages, not the messages we are sending/receiving.

**Comment by schulz2** [comment]
@chanskw:
Apart from the conflict that must be resolved (which I wasn't aware of when creating), is there a problem with this pull request?

**Comment by chanskw** [comment]
Hi @schulz2, Did we run through regression tests with all these changes?

**Comment by schulz2** [comment]
Hi @chanskw,
when we were assigned to the translation task priorities were set to get the translation resources done first and take care of the test suites afterwards. I'm not done with the latter locally. Can you point me to a testbed that has the environment for messaging toolkit up-and-running and the testsuite that has been defined as regression test suite, please?

**Comment by chanskw** [comment]
I am uncomfortable merging any code into master without testing.  The master has to remain stable and "production-ready".  Therefore, some testing need to be done for this to make sure that the operators are at least functional.

**Comment by schulz2** [comment]
I'm totally d'accord and and felt/feel uncomfortable, too, but we were thrown into this with a tough schedule. As you are one of the main contributors here, which test suite do you run before you commit?

**Comment by chanskw** [comment]
@schulz2 For us to pull in this pull request, I think we need to do this at a minimum:
1.  Please resolve the merge conflict and make sure that you are building and testing with the latest code.
2.  Please run some functional tests (manual or automatic) for all the operators in the toolkit.  You do not need to add new tests for the translation work yet.  But I think the toolkit need to be tested in English to make sure that the operators are still functional before we can deliver to master.  

If you are planning to run manual tests, you can test with the samples that are shipped with the toolkit, to make sure that we can still send and ingest data.  Otherwise, you should rerun the JUnit tests that we have.

**Comment by schulz2** [comment]
Testsuites run as successful as they run with product release v4.2.0.2

**Pull request merged**
