### PR TITLE
KafkaConsumer: Add metrics for keeping track of offsets in consistent region

### PR DESCRIPTION
**Pull request by ddebrunner**
In developing some improvements to the operator I found it useful to be able to see the current Kafka offsets as metrics (visible in the console etc.)

### CODE REVIEW

**Comment by Alex-Cook4** [comment]
Thanks @ddebrunner, these are cool additions. 

Could you highlight why we want both of these metrics? 

 * topicCkptOffsetsMetrics - Offset at the last checkpoint of this operator.
 * topicRegionCkptOffsetsMetrics - Offset at the last region completed checkpoint.

Won't these be the same as soon as regionCheckpointed is completed? Based on docs: regionCheckpointed  - Called when the whole consistent region has been drained and checkpointed.

I think I might be missing how the checkpointing api is working though, since I can't imagine why this map would ever get big in that case: ckptOffsetMaps

Wouldn't "regionCheckpointed" always get called before multiple checkpoints?

**Comment by Alex-Cook4** [comment]
Also, would it be a security concern to have the topic as a metric? I could see that being useful to be able to view from the console, even though it wouldn't really be changing.

**Comment by Alex-Cook4** [comment]
To answer my own question...if someone has the zookeeper string, they could already query the list of topics available, so probably not a security concern: 
> /usr/bin/kafka-topics --zookeeper zk01.example.com:2181 --list

**Comment by ddebrunner** [comment]
There is a potential time gap between the operator checkpointing and the region checkpointing, and once the operator supports asynchronous checkpointing the values can differ.

**Comment by ddebrunner** [comment]
If we keep with the assumption that a `KafkaConsumer` in a consistent region only ever has a single topic, then the topic can be removed and the metrics names made generic (though still need the partition).

**Comment by ddebrunner** [comment]
> I think I might be missing how the checkpointing api is working though, since I can't imagine why this map would ever get big in that case: ckptOffsetMaps

Not sure what you are asking.

**Comment by ddebrunner** [comment]
> Won't these be the same as soon as regionCheckpointed is completed?

Yes, assuming no asynchronous checkpointing, but the more interesting case is when there is a failure between the operator checkpointing and the region checkpointing, when they will be different.

**Comment by Alex-Cook4** [comment]
With regards to: 
> I think I might be missing how the checkpointing api is working though, since I can't imagine why this map would ever get big in that case: ckptOffsetMaps

I wasn't following why we are using a map here since we add an element at checkpoint, and then simply remove it when the regionCheckpointed method is called. Therefore only ever having one element. But it makes sense in the case of asynchronous checkpointing. 

I'm fine with the current metric names. I was just considering whether or not we would also want to add a topic metric, but that isn't directly related to these consistent region metrics.

**Comment by ddebrunner** [comment]
Thanks!

**Pull request merged**
