### PR TITLE
Fix for #89, 91, 94

### PR DESCRIPTION
**Pull request by conglisc**
Also merged changes with master.

### CODE REVIEW

**Comment by chanskw** [comment]
Can you please provide a brief description of the three fixes?
What is the problem and how they are fixed?

**Comment by conglisc** [comment]
Issue #89: The issue is that currently the value of provider_url must be a absolute path. The change made is to support relative path, and the relative path must be relative to the application directory, if user does not specify a value for provider_url, then it is assumed that the bidings file can be found at etc/ directory. i.e the following use cases will be supported.

provider_url="" // operator is looking for .bindings file from Application_Dir/etc/
provider_url="etc/" // Application_Dir/etc
provider_url="file:etc/" Application_Dir/etc

Issue #91: The make file of all samples is currently assuming the location of the toolkit directory at ../../com.ibm.streamsx.messaing. This works well if user compiles the sample from the github file structure. If a user compiles it from the sample shipped with the product, then this will not work as the toolkit location is  actually at ../../../toolkits/com.ibm.streamsx.messaing. To support this scenario, I have added ${STREAMS_INSTALL}/toolkits/com.ibm.streamsx.messaing in the make file, i.e STREAMS_INET_TOOLKIT ?=../../com.ibm.streamsx.messaing:${STREAMS_INSTALL}/toolkits/com.ibm.streamsx.messaing 


Issue #94: The MQTT operator requires that either the dataAttributeName parameter is used to identify the data attribute in streams schema or having an attribute that is named "data" on the stream. Otherwise the application will not compile even the streams schema only has one attribute.

The change is made to take care of use case where there is only a single attribute in the streams schema, the operator will assume this attribute is the data attribute when it is not named as "data" and the dataAtttributeName parameter is not used.

**Comment by chanskw** [comment]
In reviewing the code, we need to adjust the fix:
For #89:  In handling of the relative path, we tolerate that the schema is not specified in the url, and assume that it is using the file: schema.  I believe this is too tolerant.  We should take the string, construct the URL and then handle relative path as-is.  If the string is missing the schema and an URL cannot be constructed, then we should throw an error and give up.

**Comment by conglisc** [comment]
Updated pull request with following new changes.
1. Reworked fix for issue #89 to reflect the suggestion.
2. Fix issue #97

**Comment by chanskw** [comment]
Thanks...

**Pull request merged**
